function [state,command] = extracthumanoiddata( dataFile, controlFile )
% EXTRACTHUMANOIDDATA Pre process hummanoid_state and hummanoid_command data

    % Read files
    dataSensor = genericExtractor(dataFile);
    dataControl = genericExtractor(controlFile);

    % Group Data Status
    state.effort_j = [dataSensor.effort_j0 dataSensor.effort_j1 ...
                dataSensor.effort_j2 dataSensor.effort_j3 ...
                dataSensor.effort_j4 dataSensor.effort_j5 ...
                dataSensor.effort_j6];
    state.position_j = [dataSensor.position_j0 dataSensor.position_j1 ...
                    dataSensor.position_j2 dataSensor.position_j3 ...
                    dataSensor.position_j4 dataSensor.position_j5 ...
                    dataSensor.position_j6];
    state.velocity_j = [dataSensor.velocity_j0 dataSensor.velocity_j1 ...
                    dataSensor.velocity_j2 dataSensor.velocity_j3 ...
                    dataSensor.velocity_j4 dataSensor.velocity_j5 ...
                    dataSensor.velocity_j6];

    % Group Data Control
    command.positionControl_j = [dataControl.position_j0 dataControl.position_j1 ...
                    dataControl.position_j2 dataControl.position_j3 ...
                    dataControl.position_j4 dataControl.position_j5 ...
                    dataControl.position_j6];
    command.stiffnessControl = dataControl.stiffness_j1(end);
    command.velocityControl = dataControl.velocity_j1(end);

    % Get Exp time
    timeStatus = 10e-10*dataSensor.header_stamp_nsecs+dataSensor.header_stamp_secs;
    timeControl = 10e-10*dataControl.header_stamp_nsecs+dataControl.header_stamp_secs;
    % Change to Absolute time
    timeStart = min([timeStatus;timeControl]);
    state.time = timeStatus - timeStart;
    command.time = timeControl - timeStart;
end
